apiVersion: cert-manager.io/v1
 
kind: Certificate
metadata:
  name: krisp-dev-tls
spec:
  secretName: krisp-dev
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: krisp.dev
  dnsNames:
    - krisp.dev
    - www.krisp.dev
